django_engine/anatomy_main/anatomy_main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import main, init_page, notes, delete_note, favorites

urlpatterns = [
    path('', init_page),
    path('home/', main, name='main'),
    path('admin/', admin.site.urls),
    path("tests/", include('tests.urls')),
    path("categories/", include('categories.urls')),
    path("articles/", include('articles.urls')),
    path('atlases/', include('atlases.urls'), name='atlases'),
    path("user/", include('users.urls')),
    path("notes/", notes, name='notes'),
    path('notes/delete_note/<str:object_id>', delete_note, name="delete_note"),
    path('favorites/', favorites, name='favorites')
]

django_engine/anatomy_main/articles/urls.py
from django.urls import path

from anatomy_main import view_builder
from . import views
from .models import Article

app_name = 'articles'

urlpatterns = [
    path('', views.main, name='main'),
    path('find/', view_builder.find(Article, "articles_main_page.html"), name='find'),
    path('find_preview/', view_builder.find(Article, "find_preview_articles_component.html", 5), name='find_preview'),
    path('open/<str:article_id>/', views.open_article, name='open_article'),
    path('popular_articles/', views.list_popular_articles, name='popular_articles'),
    path('favorite_articles/', views.list_favorite_articles, name='favorite_articles'),
    path('toggle_favorite_article/<str:article_id>/', views.toggle_favorite, name='add_to_favorite'),
    path('toggle_save_note/<str:article_id>/<str:note_text>/', views.toggle_save_note, name='toggle_save_note'),
    path('atlases/<str:article_id>', views.open_atlases_by_article, name='open_atlases_by_article'),
    path('articles/<str:article_id>', views.open_tests_by_article, name='open_tests_by_article')
]

django_engine/anatomy_main/atlases/urls.py
from django.urls import path

from anatomy_main import view_builder
from . import views
from .models import Atlas

app_name = 'atlases'

urlpatterns = [
    path('', views.main, name='main'),
    path('find/', view_builder.find(Atlas, "atlases_main_page.html"), name='find'),
    path('find_preview/', view_builder.find(Atlas, "find_preview_atlases_component.html", 5), name='find_preview'),
    path('open/<str:atlas_id>/', views.open_atlas, name='open_atlas'),
    path('favorite_atlases/', views.list_favorite_atlases, name='favorite_atlases'),
    path('popular_atlases/', views.list_popular_atlases, name='popular_atlases'),
    path('toggle_favorite_atlas/<str:atlas_id>/', views.toggle_favorite, name='add_to_favorite'),
    path('toggle_save_note/<str:atlas_id>/<str:note_text>/', views.toggle_save_note, name='toggle_save_note'),
    path('toggle_save_note/<str:atlas_id>/', views.toggle_save_note, name='toggle_save_note'),
    path('articles/<str:atlas_id>', views.open_articles_by_atlases, name='open_articles_by_atlases'),
    path('tests/<str:atlas_id>', views.open_tests_by_atlases, name='open_tests_by_atlases')
]

django_engine/anatomy_main/categories/urls.py
from django.urls import path

from anatomy_main import view_builder
from . import views
from .models import Catalog

app_name = 'categories'

urlpatterns = [
    path('', views.main, name='main'),
    path('find/', view_builder.find(Catalog, "all_categories.html"), name='find'),
    path('find_preview/', view_builder.find(Catalog, "find_preview_categories_component.html", 5), name='find_preview'),
    path('favorite/<str:catalog_id>/', views.toggle_favorite, name='add_to_favorite'),
    path('open/<str:catalog_id>/', views.open_catalog, name='open_catalog'),
    path('favorite_catalogs/', views.favorite_catalogs, name='favorite_catalogs'),
    path('open_catalogs_list/', views.open_catalogs_list, name='open_catalogs_list'),
    path("set_current_category/<str:category_id>/", views.set_current_category, name='set_current_category'),
    path("unset_current_category/<str:current_path_name>", views.unset_current_category, name='unset_current_category')
]

django_engine/anatomy_main/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('list_user_completed_tests/', views.list_user_completed_tests, name='list_user_completed_tests'),
    # path('favorites/', views.favorites, name='favorites'),
    # path('notes/', views.notes, name='notes'),
]

django_engine/anatomy_main/anatomy_main/models.py
from django.db import models


class BaseModel(models.Model):
    """ Базовый класс для Тестов, Атласов и Статей """

    class Meta:
        abstract = True

    def get_tests_by_categories(self):
        """ Получение списка тестов по категориям """
        tests = set()
        for catalog in self.catalogs.all():
            if catalog.tests_ids():
                tests.update(catalog.tests_ids())

        return tests

    def get_articles_by_categories(self):
        """ Получение списка статей по категориям """
        articles = set()
        for catalog in self.catalogs.all():
            if catalog.articles_ids():
                articles.update(catalog.articles_ids())

        return articles

    def get_atlases_by_categories(self):
        """ Получение списка атласов по категориям """
        articles = set()
        for catalog in self.catalogs.all():
            if catalog.atlases_ids():
                articles.update(catalog.atlases_ids())

        return articles

django_engine/anatomy_main/anatomy_main/views.py
import hashlib
import hmac
import json
import os
import time
import urllib.parse

import requests
from articles.models import Article
from atlases.models import Atlas
from categories.models import Catalog
from django.contrib.auth import login
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from tests.models import Test
from users.models import *
from users.models import User
from anatomy_main.utils import get_current_category

# Дада снова токен в коде
# )))))))))))))
bot_token = os.getenv('BOT_TOKEN', '')
imgur_client_id = os.getenv('IMGUR_CLIENT_ID', '3dd1847a2c4f6e0')


# Функция для получения фотографии профиля пользователя
def get_user_profile_picture(user):
    user_id = user.telegram_id
    try:
        # Получаем фотографии профиля пользователя через API Telegram
        url = f'https://api.telegram.org/bot{bot_token}/getUserProfilePhotos?user_id={user_id}'
        response = requests.get(url)

        # Проверяем, что запрос прошел успешно
        if response.status_code == 200:
            data = response.json()

            # Проверяем, есть ли фотографии
            if data['result']['total_count'] > 0:
                # Получаем ID первого фото
                file_id = data['result']['photos'][0][0]['file_id']
                if user.last_telegram_photo_file_id == file_id:
                    return None

                # Получаем информацию о файле
                file_url = f'https://api.telegram.org/bot{bot_token}/getFile?file_id={file_id}'
                file_response = requests.get(file_url)

                if file_response.status_code == 200:
                    file_data = file_response.json()
                    file_path = file_data['result']['file_path']
                    file_download_url = f'https://api.telegram.org/file/bot{bot_token}/{file_path}'

                    # Загружаем файл с Telegram
                    file_content = requests.get(file_download_url).content

                    # Отправляем файл на Imgur
                    headers = {'Authorization': f'Client-ID {imgur_client_id}'}
                    imgur_response = requests.post(
                        url='https://api.imgur.com/3/upload',
                        headers=headers,
                        files={'image': file_content}
                    )

                    if imgur_response.status_code == 200:
                        imgur_data = imgur_response.json()
                        return {'link': imgur_data['data']['link'], 'file_id': file_id}
                    else:
                        print("Ошибка при загрузке на Imgur:", imgur_response.json())
                        return None
                else:
                    print("Ошибка при получении файла.")
                    return None
            else:
                print("У пользователя нет фотографий.")
                return None
        else:
            print(f"Ошибка при запросе данных: {response.status_code}")
            return None
    except Exception as e:
        print(f"Ошибка: {e}")
        return None


# Функция для проверки подписи Telegram
def verify_telegram_signature(init_data, bot_token):
    parsed_data = dict(urllib.parse.parse_qsl(init_data))
    check_hash = parsed_data.pop('hash', None)

    data_check_string = "\n".join([f"{key}={value}" for key, value in sorted(parsed_data.items())])
    secret_key = hmac.new(b"WebAppData", bot_token.encode('utf-8'), hashlib.sha256).digest()

    calculated_hash = hmac.new(secret_key, data_check_string.encode('utf-8'), hashlib.sha256).hexdigest()

    return check_hash == calculated_hash, parsed_data


# Функция для сохранения или обновления данных пользователя
def save_or_update_user(parsed_data):
    user_data = json.loads(parsed_data.get('user', '{}'))
    telegram_id = user_data.get('id')
    first_name = user_data.get('first_name', '')
    last_name = user_data.get('last_name', '')
    telegram_username = user_data.get('username', '')
    username = f"tg_{telegram_id}"

    if telegram_id:
        user, created = User.objects.get_or_create(telegram_id=telegram_id, defaults={
            'username': username,
            'telegram_username': telegram_username,
            'telegram_id': telegram_id,
            'first_name': first_name,
            'last_name': last_name,
        })

        if not created:
            # Обновляем данные пользователя, если они изменились
            if user.first_name != first_name or user.last_name != last_name or user.telegram_username != telegram_username or user.username != username:
                user.username = username
                user.first_name = first_name
                user.last_name = last_name
                user.telegram_username = telegram_username
        telegram_photo_data = get_user_profile_picture(user)
        if telegram_photo_data:
            user.telegram_photo_url = telegram_photo_data['link']
            user.last_telegram_photo_file_id = telegram_photo_data['file_id']
        user.save()
        return user
    return None


def build_url_from_start_param(start_param):
    try:
        if '_' in start_param:
            resource_type, resource_id = start_param.split('_', 1)
            if resource_type == 'article':
                return reverse('articles:open_article', args=[resource_id])
            elif resource_type == 'test':
                return reverse('tests:open_test', args=[resource_id])
            elif resource_type == 'atlas':
                return reverse('atlases:open_atlas', args=[resource_id])
            elif resource_type == 'category':
                return reverse('categories:open_catalog', args=[resource_id])
            elif resource_type == 'note':
                return reverse('delete_note', args=[resource_id])
        else:
            if start_param == 'profile':
                return reverse('users:profile')
            elif start_param == 'favorites':
                return reverse('favorites')
            elif start_param == 'notes':
                return reverse('notes')
            elif start_param == 'popular_tests':
                return reverse('tests:list_popular_tests')
            elif start_param == 'popular_articles':
                return reverse('popular_articles')
            elif start_param == 'popular_atlases':
                return reverse('atlases:popular_atlases')
        return None
    except Exception as e:
        print(f"Error building URL from start_param: {e}")
        return None


# Основная view для обработки данных
def main(request):
    # Получаем данные пользователя из GET-запроса
    init_data = request.GET.get('user_data')

    category = get_current_category(request)

    popular_tests = Test.get_popular(count=6, current_category=category)
    popular_atlases = Atlas.get_popular(count=6, current_category=category)
    popular_articles = Article.get_popular(count=6, current_category=category)
    if not init_data and request.user.is_authenticated:
        return render(request, 'main.html', context={'user': request.user,
                                                     'popular_tests': popular_tests,
                                                     'popular_atlases': popular_atlases,
                                                     'popular_articles': popular_articles,
                                                     'category': category})

    if init_data:
        # Проверяем подпись Telegram
        is_valid, parsed_data = verify_telegram_signature(init_data, bot_token)
        if is_valid:
            # Проверяем дату авторизации, чтобы данные не устарели
            auth_date = int(parsed_data.get('auth_date', 0))
            if time.time() - auth_date > 5 * 60:  # Данные не старше 5 минут
                return JsonResponse({'status': 'error', 'message': 'Data is outdated'}, status=403)

            # Сохраняем или обновляем пользователя
            user = save_or_update_user(parsed_data)
            start_params = parsed_data.get('start_param', None)

            if user:
                login(user=user, request=request)
                if start_params:
                    redirect_url = build_url_from_start_param(start_params)
                    if redirect_url:
                        return redirect(redirect_url)

                return render(request, 'main.html', context={'user': request.user,
                                                             'popular_tests': popular_tests,
                                                             'popular_atlases': popular_atlases,
                                                             'popular_articles': popular_articles})
        return JsonResponse({'status': 'error', 'message': 'Invalid signature'}, status=403)

    return JsonResponse({'status': 'error', 'message': 'No user data provided'}, status=400)


# Вспомогательная view для редиректа на main
def init_page(request):
    return render(request, 'index_auth_redirect.html', context={'auth_url': reverse('main')})


def test(request):
    return render(request, 'test.html', context={'user': request.user})


def notes(request):
    return render(request, 'notes.html', context=request.user.get_notes())


def delete_note(request, object_id):
    object_ = None
    if TestUserRel.objects.filter(test_id=object_id).exists():
        print('test')
        object_ = TestUserRel.objects.get(test_id=object_id)
    elif AtlasUserRel.objects.filter(atlas_id=object_id).exists():
        print('atlas')
        object_ = AtlasUserRel.objects.get(atlas_id=object_id)
    elif ArticleUserRel.objects.filter(article_id=object_id).exists():
        print('article')
        object_ = ArticleUserRel.objects.get(article_id=object_id)
    print(object_)
    if object_:
        object_.note = ""
        object_.save()

    return redirect("notes")


def favorites(request):

django_engine/anatomy_main/anatomy_main/templates/current_category_label.html
{% load static %}
{% if category %}
    <div class="text-start pb-3">
        <h6>Тема - <strong>{{ category }}</strong>
            <span class="badge rounded-pill text-bg-primary" style="font-size: 16px !important;">{{ active }}</span>
            <a class="link" href="{% url 'categories:unset_current_category' request.resolver_match.view_name %}"
               style="color: #335B5A">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 33 33" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                     class="icon icon-tabler icons-tabler-outline icon-tabler-x text-center justify-content-center">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                    <path d="M18 6l-12 12"/>
                    <path d="M6 6l12 12"/>
                </svg>
            </a>
        </h6>
    </div>
{% endif %}

django_engine/anatomy_main/anatomy_main/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<nav class="navbar navbar-expand-lg sticky-top" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand p-0" href="{% url 'main' %}" onclick="hapticFeedback()">
      <img src="{% static 'icons/logo.png' %}" alt="Logo" width="40" height="40" class="d-inline-block align-text-center">
        <span>Vet Moment</span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
            <div class="row">
                <div class="col-6">
                    <div class="col-12 pb-2 pt-1">
                        <img src="{{ user.telegram_photo_url }}" style="height: auto;
                        max-width: 100%; max-height: 80px" class="rounded-4 shadow">
                    </div>
                    <div class="col-12 pb-3 pt-3" style="color: white">
                        <label>{% if user.first_name %} {{ user.first_name }} {{ user.last_name }}{% else %} Неопознанный {% endif %}</label>
                    </div>
                </div>
                <div class="col-6 justify-content-end">
                    <div class="col-12 d-inline-flex justify-content-end pt-1 pb-2" style="max-height: 92px; height: 92px">
                        <button type="button" class="btn-close pt-3" data-bs-dismiss="offcanvas" aria-label="Close" style="color: white; opacity: 100%;"></button>
                    </div>
                    <div class="col-12 d-inline-flex justify-content-end pb-3 pt-3">
                        <label>{{ user.get_count_days_on_platform }} дней на сайте</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="offcanvas-body">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link icon-link" style="text-decoration: none; color: white" href="{% url 'users:profile' %}" role="button" onclick="hapticFeedback()">
                      <label><svg  xmlns="http://www.w3.org/2000/svg"  width="20"  height="20"
                          viewBox="0 0 24 24"  fill="none"  stroke="currentColor"
                          stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"
                          class="icon icon-tabler icons-tabler-outline icon-tabler-user-square-rounded">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <path d="M12 13a3 3 0 1 0 0 -6a3 3 0 0 0 0 6z" />
                        <path d="M12 3c7.2 0 9 1.8 9 9s-1.8 9 -9 9s-9 -1.8 -9 -9s1.8 -9 9 -9z" />
                        <path d="M6 20.05v-.05a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v.05" />
                    </svg>
                          </label>
                      Мой профиль
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link icon-link" style="text-decoration: none; color: white" href="{% url "notes" %}">
                      <label><svg  xmlns="http://www.w3.org/2000/svg"  width="20"  height="20"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-bookmarks">
                          <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                          <path d="M15 10v11l-5 -3l-5 3v-11a3 3 0 0 1 3 -3h4a3 3 0 0 1 3 3z" />
                          <path d="M11 3h5a3 3 0 0 1 3 3v11" />
                      </svg></label>
                      Заметки</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link icon-link" style="text-decoration: none; color: white" href="{% url 'favorites' %}">
                      <label>
                          <svg  xmlns="http://www.w3.org/2000/svg"  width="20"  height="20"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-star">
                              <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                              <path d="M12 17.75l-6.172 3.245l1.179 -6.873l-5 -4.867l6.9 -1l3.086 -6.253l3.086 6.253l6.9 1l-5 4.867l1.179 6.873z" />
                          </svg>
                      </label>
                      Избранное</a>
                </li>
            </ul>
            <hr class="hr"/>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link icon-link" style="text-decoration: none; color: white" href="{% url 'tests:main' %}">
                      <label>
                          <svg  xmlns="http://www.w3.org/2000/svg"  width="20"  height="20"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-checklist">
                              <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                              <path d="M9.615 20h-2.615a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v8" />
                              <path d="M14 19l2 2l4 -4" />
                              <path d="M9 8h4" />
                              <path d="M9 12h2" />
                          </svg>
                      </label>
                      Посмотреть тесты</a>
                </li>
                <li class="nav-item icon-link">
                  <a class="nav-link {% if active == 'atlases' %} active {% endif %}" href="{% url 'atlases:main' %}" style="text-decoration: none; color: white">
                      <label>
                          <svg  xmlns="http://www.w3.org/2000/svg"  width="20"  height="20"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-checklist">
                              <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                              <path d="M9.615 20h-2.615a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v8" />
                              <path d="M14 19l2 2l4 -4" />
                              <path d="M9 8h4" />
                              <path d="M9 12h2" />
                          </svg>
                      </label>
                      Посмотреть атласы</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link icon-link" href="{% url 'articles:main' %}" style="text-decoration: none; color: white">
                      <label>
                          <svg  xmlns="http://www.w3.org/2000/svg"  width="20"  height="20"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-checklist">
                              <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                              <path d="M9.615 20h-2.615a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v8" />
                              <path d="M14 19l2 2l4 -4" />
                              <path d="M9 8h4" />
                              <path d="M9 12h2" />
                          </svg>
                      </label>
                      Посмотреть статьи</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link icon-link" href="{% url 'categories:main' %}" style="text-decoration: none; color: white">
                      <label>
                          <svg  xmlns="http://www.w3.org/2000/svg"  width="20"  height="20"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-checklist">
                              <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                              <path d="M9.615 20h-2.615a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v8" />
                              <path d="M14 19l2 2l4 -4" />
                              <path d="M9 8h4" />
                              <path d="M9 12h2" />
                          </svg>
                      </label>
                      Посмотреть категории</a>
                </li>
            </ul>
            <hr class="hr"/>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a href="{% url 'users:list_user_completed_tests' %}" class="nav-link icon-link" style="text-decoration: none; color: white">
                        <label>
                            <svg  xmlns="http://www.w3.org/2000/svg"  width="20"  height="20"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-notes">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <path d="M5 3m0 2a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2z" />
                                <path d="M9 7l6 0" /><path d="M9 11l6 0" />
                                <path d="M9 15l4 0" />
                            </svg>
                        </label>
                        Пройденные тесты</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'tests:retry_last_test' %}" class="nav-link icon-link" style="text-decoration: none; color: white">
                        <label>
                          <svg  xmlns="http://www.w3.org/2000/svg"  width="20"  height="20"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-checklist">
                              <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                              <path d="M9.615 20h-2.615a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v8" />
                              <path d="M14 19l2 2l4 -4" />
                              <path d="M9 8h4" />
                              <path d="M9 12h2" />
                          </svg>
                      </label>
                        Перепройти последний тест</a>
                </li>
            </ul>
            {% if user.is_staff %}
                <hr class="hr"/>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a href="/admin/" class="nav-link icon-link" style="text-decoration: none; color: white">
                            <svg  xmlns="http://www.w3.org/2000/svg"  width="20"  height="20"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-settings">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <path d="M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065z" />
                                <path d="M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0" />
                            </svg>
                            Админка
                        </a>
                    </li>
                </ul>
            {% endif %}
        </div>
    </div>
  </div>
</nav>

<script>
    // // Инициализация WebApp API
    // const tg = window.Telegram.WebApp;
    //
    // // Проверка готовности WebApp
    // tg.ready();

    // Функция для легкой вибрации
    function hapticFeedback() {
        tg.HapticFeedback.impactOccurred('medium');
        ;  // Включение вибрации
    }
</script>

django_engine/anatomy_main/anatomy_main/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://telegram.org/js/telegram-web-app.js"></script>
</head>
<body>
  {{user.username}}
    <h1>Telegram User Data</h1>
    <pre id="user-data" style="color: red;">Loading...</pre>
</body>
<script>
        // Инициализация WebApp API
        const tg = window.Telegram.WebApp;

        // Проверка готовности WebApp
        tg.ready();

        // Получаем все данные из initDataUnsafe
        const initData = tg.initDataUnsafe;

        // Отображаем полученные данные на странице
        const userDataElement = document.getElementById('user-data');
        userDataElement.textContent = JSON.stringify(initData, null, 2); // Преобразуем объект в JSON-формат с отступами
    </script>
</html>