django_engine/anatomy_main/anatomy_main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import main, init_page, notes, delete_note, favorites

urlpatterns = [
    path('', init_page),
    path('home/', main, name='main'),
    path('admin/', admin.site.urls),
    path("tests/", include('tests.urls')),
    path("categories/", include('categories.urls')),
    path("articles/", include('articles.urls')),
    path('atlases/', include('atlases.urls'), name='atlases'),
    path("user/", include('users.urls')),
    path("notes/", notes, name='notes'),
    path('notes/delete_note/<str:object_id>', delete_note, name="delete_note"),
    path('favorites/', favorites, name='favorites')
]

django_engine/anatomy_main/atlases/urls.py
from django.urls import path

from anatomy_main import view_builder
from . import views
from .models import Atlas

app_name = 'atlases'

urlpatterns = [
    path('', views.main, name='main'),
    path('find/', view_builder.find(Atlas, "atlases_main_page.html"), name='find'),
    path('find_preview/', view_builder.find(Atlas, "find_preview_atlases_component.html", 5), name='find_preview'),
    path('open/<str:atlas_id>/', views.open_atlas, name='open_atlas'),
    path('favorite_atlases/', views.list_favorite_atlases, name='favorite_atlases'),
    path('popular_atlases/', views.list_popular_atlases, name='popular_atlases'),
    path('toggle_favorite_atlas/<str:atlas_id>/', views.toggle_favorite, name='add_to_favorite'),
    path('toggle_save_note/<str:atlas_id>/<str:note_text>/', views.toggle_save_note, name='toggle_save_note'),
    path('toggle_save_note/<str:atlas_id>/', views.toggle_save_note, name='toggle_save_note'),
    path('articles/<str:atlas_id>', views.open_articles_by_atlases, name='open_articles_by_atlases'),
    path('tests/<str:atlas_id>', views.open_tests_by_atlases, name='open_tests_by_atlases')
]

django_engine/anatomy_main/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('list_user_completed_tests/', views.list_user_completed_tests, name='list_user_completed_tests'),
    # path('favorites/', views.favorites, name='favorites'),
    # path('notes/', views.notes, name='notes'),
]

django_engine/anatomy_main/atlases/models.py
import uuid

from anatomy_main.models import BaseModel
from django.db import models
from django.urls import reverse
from users.models import AtlasUserRel


class Atlas(BaseModel):
    id = models.CharField(max_length=100, default=uuid.uuid4, primary_key=True)
    label = models.CharField(max_length=200, verbose_name='Название файла')
    atlas_file = models.ImageField(verbose_name='Файл атласа', upload_to='atlases_storage')
    catalogs = models.ManyToManyField("categories.Catalog", verbose_name="Принадлежит каталогам",
                                      related_name='atlases', blank=True)
    description = models.CharField(verbose_name="Текст атласа", max_length=1000, default='')
    tooltips = models.JSONField(verbose_name='Координаты подсказок', default=dict)

    class Meta:
        verbose_name = 'Атлас'
        verbose_name_plural = 'Атласы'

    def child_ids(self):
        cls = type(self)
        if self.child.all():
            children = [cls.objects.get(id=child.id) for child in self.child.all()]
            return children
        return []

    def get_absolute_url(self):
        return reverse("atlases:open_atlas", kwargs={"atlas_id": self.id})

    @classmethod
    def get_favorite_atlases(cls, user):
        return cls.objects.filter(
            id__in=AtlasUserRel.objects.filter(user=user, is_favorite=True).values('atlas_id')
        ).annotate(
            is_favorite=models.Value(True, output_field=models.BooleanField())
        )

    @classmethod
    def get_popular(cls, count: int, current_category=None):
        if current_category:
            exp = f"""WITH atlas_results AS (SELECT atlases_atlas.* 
                                      FROM atlases_atlas_catalogs 
                                      LEFT JOIN atlases_atlas ON atlases_atlas_catalogs.atlas_id = atlases_atlas.id
                                      WHERE atlases_atlas_catalogs.catalog_id = '{current_category.id}')
                                      SELECT atlas_results.*
                                      FROM atlas_results
            """
        else:
            exp = """SELECT atlas_results.*
                     FROM atlases_atlas AS atlas_results
                  """

        res = cls.objects.raw(
            f"""
            {exp}
            LEFT JOIN (
                SELECT atlas_user.atlas_id,
                       COUNT(atlas_user.atlas_id) AS fav_count
                FROM atlas_user
                WHERE atlas_user.is_favorite
                GROUP BY atlas_user.atlas_id
            ) AS F ON F.atlas_id = atlas_results.id
            ORDER BY F.fav_count DESC
            """
        )
        return res[:count]

    def __str__(self):
        return self.label

django_engine/anatomy_main/atlases/views.py
from anatomy_main import utils
from categories.models import Catalog
from django.db.models import Q
from django.http import HttpRequest
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from users.models import AtlasUserRel

from .models import Atlas
from anatomy_main.utils import get_current_category


def main(request: HttpRequest):

    current_category = get_current_category(request)

    popular_atlases = Atlas.get_popular(10, current_category=current_category)
    favorite_atlases = Atlas.get_favorite_atlases(request.user)

    categories = Catalog.objects.all()
    return render(request, 'atlases_main_page.html', {
        'popular_atlases': popular_atlases,
        'favorite_atlases': favorite_atlases,
        'categories': categories,
        'category': current_category
    })


def open_atlas(request: HttpRequest,
               atlas_id: str):
    atlas = get_object_or_404(Atlas, id=atlas_id)
    atlas_user_rel: AtlasUserRel = AtlasUserRel.objects.get_or_create(user=request.user,
                                                                      atlas_id=atlas_id)[0]

    if request.method == "POST":
        utils.toggle_save_note(request, atlas_id, AtlasUserRel, 'atlas_id', request.POST.get("note"))

    try:
        rel_field = AtlasUserRel.objects.get(atlas=atlas, user=request.user)
    except AtlasUserRel.DoesNotExist:
        note = ''
    else:
        note = rel_field.note

    return render(request,
                  'atlas.html',
                  {
                      "atlas": atlas,
                      'tests': atlas.get_tests_by_categories(),
                      'articles': atlas.get_articles_by_categories(),
                      "is_favorite": atlas_user_rel.is_favorite,
                      'note': note
                  })


@require_POST
def toggle_save_note(request, atlas_id, note_text=''):
    return utils.toggle_save_note(request, atlas_id, AtlasUserRel, 'atlas_id', note_text)


@require_POST
def toggle_favorite(request: HttpRequest,
                    atlas_id: str):
    return utils.toggle_favorite(request,
                                 atlas_id,
                                 AtlasUserRel,
                                 "atlas_id")


def list_favorite_atlases(request):
    return render(request, 'list_atlases_page.html', context={"atlases": Atlas.get_favorite_atlases(request.user)})


def list_popular_atlases(request):

    current_category = get_current_category(request)

    return render(request,
                  'list_atlases_page.html',
                  context={"atlases": Atlas.get_popular(count=10, current_category=current_category),
                           'category': current_category})


def find(request: HttpRequest):
    queries = request.GET
    atlases = Atlas.objects.filter(Q(label__icontains=queries.get('label', '')))
    return render(request, 'atlas_find.html', {'atlases': atlases})


def open_articles_by_atlases(request, atlas_id: str):
    atlas = get_object_or_404(Atlas, id=atlas_id)
    return render(request, "list_articles_page.html", context={'articles': atlas.get_articles_by_categories()})


def open_tests_by_atlases(request, atlas_id: str):
    atlas = get_object_or_404(Atlas, id=atlas_id)
    return render(request, "list_tests_page.html", context={'tests': atlas.get_tests_by_categories()})

django_engine/anatomy_main/atlases/templates/add_atlas_to_favorite.html
{% load static %}
<label>
    <button class="favorite-button btn-link p-0 m-0 w-100" style="border: 0; text-decoration: none; background: none" data-item-id="{{ atlas.id }}">
        {% if is_favorite %}<img id="test" src="{% static 'icons/star_black.svg' %}" class="star-icon">{% else %}<img id='test' src="{% static 'icons/star.svg' %}" class="star-icon">{% endif %}
    </button>
</label>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% csrf_token %}
<script>
const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
</script>
<script>
    $(document).ready(function() {
        $('.favorite-button ').click(function() {
            var button = $(this);
            var atlasId = button.data('item-id');
            var oldIcon = document.getElementById('test')
            $.ajax({
                url: '/atlases/toggle_favorite_atlas/' + atlasId + '/',
                type: 'POST',
                headers: {
                    'X-CSRFToken': csrftoken
                },
                success: function(response) {
                    if (response.action === 'added') {
                        var newIcon = document.createElement('img')
                        newIcon.setAttribute('class', 'star-icon')
                        newIcon.setAttribute('id', 'test')
                        newIcon.setAttribute('src', "{% static 'icons/star_black.svg' %}")
                        oldIcon.parentNode.replaceChild(newIcon, oldIcon)
                        console.log(response.action)
                    } else {
                        var newIcon = document.createElement('img')
                        newIcon.setAttribute('class', 'star-icon')
                        newIcon.setAttribute('id', 'test')
                        newIcon.setAttribute('src', "{% static 'icons/star.svg' %}")
                        oldIcon.replaceWith(newIcon)
                        console.log(response.action)
                    }
                },
                error: function(xhr, status, error) {
                    console.error("Ошибка:", error);
                }
            });
        });
    });
</script>

django_engine/anatomy_main/atlases/templates/add_note_to_atlas.html
<div class="input-group mb-3 mt-3 notes-component" style="border-radius: 20px;">
    <input type="text" name="note" class="form-control search-input rounded-start-pill border border-0"
           placeholder="Написать заметку по теме"
           style="border-right: none; background-color: white; border-color: rgb(0,0,0)" value="{{ note }}"
           id="textareaID">
    <button class="btn btn-outline-secondary rounded-end-circle save-button border border-0"
            data-bs-toggle="tooltip"
            data-bs-placement="top"
            data-bs-title="Добавить"
            style="border-left: none; border-color: rgb(0,0,0); background-color: white">
        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#113B3A"
             stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
             class="icon icon-tabler icons-tabler-outline icon-tabler-plus">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
            <path d="M12 5l0 14"/>
            <path d="M5 12l14 0"/>
        </svg>
    </button>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% csrf_token %}
<script>
    $(document).ready(function () {
        $('.save-button ').click(function () {
            var button = $(this);
            console.log(button)
            var note_text = document.getElementById('textareaID').value;
            $.ajax({
                url: '/atlases/toggle_save_note/' + '{{ atlas.id }}' + "/" + note_text + (note_text ? '/' : ''),
                type: 'POST',
                headers: {
                    'X-CSRFToken': csrftoken
                },
                success: function (response) {
                    console.log(response)
                },
                error: function (xhr, status, error) {
                    console.error("Ошибка:", error);
                }
            });
        });
    });
</script>
<script>
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>

django_engine/anatomy_main/atlases/templates/atlases_main_page.html
{% include 'index.html' with active='atlases' %}
{% load static %}
{% block content %}
    <div class="container p-4">

        {% include 'current_category_label.html' with active='Атласы' %}

        <form action="{% url 'atlases:find' %}">
            <div class="input-group mb-3"
                 style="border-radius: 20px; position: relative;">
                <div class='input-group' style="position: relative; overflow: hidden; margin-bottom: -10px; !important">
                    <input name="label__icontains" type="text"
                           class="form-control search-input custom-focus rounded-start-pill notes-component"
                           placeholder="Найти атлас"
                           style="border-right: none; background-color: white"
                           autocomplete="off">
                    <button class="btn btn-outline-secondary rounded-end-circle notes-component"
                            style="border-left: none; background-color: white">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none"
                             stroke="#113B3A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                             class="icon icon-tabler icons-tabler-outline icon-tabler-search">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M10 10m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"/>
                            <path d="M21 21l-6 -6"/>
                        </svg>
                    </button>
                </div>
                <!-- Выпадающее меню результатов -->
                <ul class="dropdown-menu w-100 shadow-lg" id="search-dropdown"
                    style="display: none; max-height: 200px; overflow-y: auto; margin-top: -10px; z-index: 1;">
                    <div id="search-results"></div>
                </ul>
            </div>
        </form>

        {% include "open_categories_button.html" %}

        {% if objects  is not None %}

            <div class="row text-center justify-content-between">
                {% if objects|length > 0 %}
                    <h1 class="p-1">Найденные атласы</h1>
                    {% include 'grid_atlases_cards.html' with atlases=objects %}
                {% else %}
                    <h1 class="p-1">Ничего не найдено</h1>
                {% endif %}
            </div>
        {% else %}
            <div class="pb-3 pt-3">
                {% include 'popular_atlases_component.html' with popular_atlases=popular_atlases %}
            </div>
            <div class="pb-3">
                {% include 'favorite_atlases_component.html' with favorite_atlases=favorite_atlases %}
            </div>
        {% endif %}

    </div>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const searchInput = document.querySelector(".search-input");
            const resultsContainer = document.querySelector("#search-results");
            const searchDropdown = document.querySelector("#search-dropdown");

            // Функция для показа/скрытия выпадающего меню
            function toggleDropdown(show) {
                searchDropdown.style.display = show ? "block" : "none";
            }

            // Закрытие меню при клике вне области
            document.addEventListener("click", function (e) {
                if (!e.target.closest(".input-group")) {
                    toggleDropdown(false);
                }
            });

            function debounce(func, delay) {
                let timeout;
                return function (...args) {
                    clearTimeout(timeout);
                    timeout = setTimeout(() => func.apply(this, args), delay);
                };
            }

            function performSearch() {
                const query = searchInput.value.trim();

                if (!query) {
                    resultsContainer.innerHTML = "";
                    toggleDropdown(false);
                    return;
                }

                toggleDropdown(true);

                fetch(`find_preview/?label__icontains=${encodeURIComponent(query)}`)
                    .then(response => {
                        if (!response.ok) throw new Error("Network response was not ok");
                        return response.text();
                    })
                    .then(html => {
                        resultsContainer.innerHTML = html;

                        // Добавляем обработчики для элементов меню
                        document.querySelectorAll("#search-dropdown .dropdown-item").forEach(item => {
                            item.addEventListener("click", function () {
                                toggleDropdown(false);
                            });
                        });
                    })
                    .catch(() => {
                        resultsContainer.innerHTML = `
                    <div class="dropdown-item text-danger">
                        Произошла ошибка. Попробуйте снова.
                    </div>`;
                    });
            }

            const debouncedSearch = debounce(performSearch, 300);

            searchInput.addEventListener("input", debouncedSearch);
            searchInput.addEventListener("focus", function () {
                if (searchInput.value.trim() && resultsContainer.innerHTML) {
                    toggleDropdown(true);
                }
            });
        });
    </script>
{% endblock %}

django_engine/anatomy_main/atlases/templates/favorite_atlases_component.html
{% load static %}
{% block favorite_atlas %}
    <div class="mb-3">
        <h2 class="h3 mb-2">Избранные атласы</h2>
        {% include "scrollable_atlases_cards_large.html" with atlases=favorite_atlases %}
        <a href="{% url 'atlases:favorite_atlases' %}"><button class="btn btn-primary btn-sm mt-2 rounded-4 shadow-lg"><span class='m-2' style="margin-right: 1px !important">Посмотреть все</span> <svg  xmlns="http://www.w3.org/2000/svg"  width="18"  height="18"  viewBox="0 0 24 24"  fill="currentColor"  class="icon icon-tabler icons-tabler-filled icon-tabler-circle-arrow-up-right"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-2 4.66h-6l-.117 .007a1 1 0 0 0 -.883 .993l.007 .117a1 1 0 0 0 .993 .883h3.584l-4.291 4.293l-.083 .094a1 1 0 0 0 1.497 1.32l4.293 -4.293v3.586l.007 .117a1 1 0 0 0 1.993 -.117v-6l-.007 -.117l-.029 -.149l-.035 -.105l-.054 -.113l-.071 -.111a1.01 1.01 0 0 0 -.097 -.112l-.09 -.08l-.096 -.067l-.098 -.052l-.11 -.044l-.112 -.03l-.126 -.017l-.075 -.003z" /></svg></button></a>
    </div>
{% endblock %}

django_engine/anatomy_main/atlases/templates/favorite_grid_atlases_cards.html
{% load static %}
{% block content %}
    {% for atlas in atlases %}
      <div class="col-6 p-1 text-start d-flex justify-content-center text-center">
        <div class="card draggable-lg border-0 shadow rounded-4 position-relative overflow-hidden">
          <a href="{{ atlas.get_absolute_url }}" style="text-decoration: none;">
            <img src="{% static atlas.atlas_file %}" class="card-img-top rounded-top-4" alt="..." onerror="this.src='{% static "alternate_imgs/kotek.png" %}'; this.onerror=null;">
          </a>

          <!-- Кнопки действий -->
          <div class="action-buttons position-absolute bottom-25 start-0 w-100 d-flex justify-content-end gap-2 px-2" style="z-index: 2; bottom: 60px">
            <!-- Избранное -->
            <button class="favorite-atlas-button btn p-1 d-flex align-items-center justify-content-center"
                    data-item-id="{{ atlas.id }}"
                    style="background-color: #345; border-radius: 0.5rem; width: 32px; height: 32px;">
{#            <img src="{% static 'icons/star_off.svg' %}" class="w-100 h-100 object-fit-contain" alt="★">#}
              {% if atlas.is_favorite %}
                <img src="{% static 'icons/star_off.svg' %}" class="w-100 h-100 object-fit-contain" alt="★">
              {% else %}
                <img src="{% static 'icons/star.svg' %}" class="w-100 h-100 object-fit-contain" alt="☆">
              {% endif %}
            </button>

            <!-- Поделиться -->
            <button class="share-atlas-button btn p-1 d-flex align-items-center justify-content-center"
                    style="background-color: #345; border-radius: 0.5rem; width: 32px; height: 32px;"
                    data-bs-toggle="modal"
                    data-bs-target="#shareModal"
                    data-atlas-id="{{ atlas.id }}"
                    data-atlas-label="{{ atlas.label|escapejs }}">
              <img src="{% static 'icons/share.svg' %}" class="w-100 h-100 object-fit-contain" alt="Share">
            </button>
          </div>

          <div class="card-body text-truncate">
            <span>{{ atlas }}</span>
          </div>
        </div>
      </div>
    {% endfor %}
    <!-- Модальное окно для выбора способа шаринга -->
    <div class="modal fade" id="shareModal" tabindex="-1" aria-labelledby="shareModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="shareModalLabel">Поделиться атласом</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="d-grid gap-2">

                        <!-- Кнопка для системного шаринга -->
                        <button class="btn btn-primary shadow-lg" onclick="shareAtlasViaSystem()">
                            <i class="bi bi-share"></i> Через приложения
                        </button>

                        <!-- Кнопка для копирования ссылки -->
                        <button class="btn btn-primary shadow-lg"
                                onclick="copyAtlasLink(); $('#shareModal').modal('hide')">
                            <i class="bi bi-link-45deg"></i> Скопировать ссылку
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% csrf_token %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

  $(document).ready(function () {
    $('.favorite-atlas-button').on('click', function (e) {
      e.preventDefault();
      e.stopPropagation();

      const buttonAtlas = $(this);
      const atlasId = buttonAtlas.data('item-id');

      // Запрос на добавление или удаление из избранного
      $.ajax({
        url: '/atlases/toggle_favorite_atlas/' + atlasId + '/',
        type: 'POST',
        headers: {
          'X-CSRFToken': csrftoken
        },
        success: function (response) {
          const icon = buttonAtlas.find('img');

          if (response.action === 'added') {
            icon.attr('src', "{% static 'icons/star_off.svg' %}");
          } else {
            icon.attr('src', "{% static 'icons/star.svg' %}");
          }
        },
        error: function (xhr, status, error) {
          console.error("Ошибка:", error);
        }
      });
    });
  });
</script>
<script>
    let currentAtlasId = null;
    let currentAtlasLabel = null;

    document.addEventListener('DOMContentLoaded', function () {
        // Обработчик нажатия на любую кнопку share-button
        document.querySelectorAll('.share-atlas-button').forEach(button => {
            button.addEventListener('click', function () {
                currentAtlasId = this.getAttribute('data-atlas-id');
                currentAtlasLabel = this.getAttribute('data-atlas-label');
            });
        });
    });

    // Генерация ссылки
    function generateAtlasShareLink() {
        return `https://t.me/vet_irit_bot?startapp=atlas_${currentAtlasId}`;
    }

    // Системный шаринг через Web Share API
    function shareAtlasViaSystem() {
        const shareData = {
            title: currentAtlasLabel || 'Атлас',
            text: 'Посмотрите этот атлас:',
            url: generateAtlasShareLink()
        };

        if (navigator.share) {
            navigator.share(shareData);
        } else {
            copyAtlasLink();
            alert('Ссылка скопирована в буфер обмена');
        }
    }

    // Копирование ссылки
    function copyAtlasLink() {
        const link = generateAtlasShareLink();
        navigator.clipboard.writeText(link).then(() => {
            if (window.Telegram && Telegram.WebApp) {
                Telegram.WebApp.showAlert('Ссылка скопирована!');
            }
        });
    }
</script>
{% endblock %}

django_engine/anatomy_main/atlases/templates/find_preview_atlases_component.html
{% load static %}
{% block find_preview_atlas %}
    <div class="mt-3 text-start">
        {% if objects|length > 0 %}
            {% for atlas in objects %}
            <li>
                <a class='dropdown-item' href="{{ atlas.get_absolute_url }}" style="text-decoration: none;">
                    <h4>{{ atlas }}</h4>
                    {% if atlas.description %}
                        {{ atlas.description|truncatechars:25 }}
                    {% else %}
                        <span>Описание отсутствует</span>
                    {% endif %}
                </a>
            </li>
            {% endfor %}
        {% else %}
            <div class="text-center mt-4">
                <p>Ничего не найдено</p>
            </div>
        {% endif %}
    </div>
{% endblock %}

django_engine/anatomy_main/atlases/templates/grid_atlases_cards.html
{% load static %}
{% block content %}
{% for atlas in atlases %}
    <div class="col-6 p-1 text-start d-flex justify-content-center text-center">
        <a href="{{ atlas.get_absolute_url }}" style="text-decoration: none;">
            <div class="card draggable-lg border-0 shadow rounded-4">
                <img src="{% static atlas.atlas_file %}" class="card-img-top rounded-top-4" alt="...">
                <div class="card-body">
                    <span>{{ atlas }}</span>
                </div>
            </div>
        </a>
    </div>
{% endfor %}
{% endblock %}

django_engine/anatomy_main/atlases/templates/list_atlases_page.html
{% include 'index.html' with active='atlases' %}
{% load static %}
{% block content %}
    <div class="container p-4 pt-3">

        {% include 'current_category_label.html' with active='Атласы' %}

        <div class="row text-center justify-content-between">
        <h1 class="p-1">Список атласов</h1>
        {% include 'grid_atlases_cards.html' with atlases=atlases %}
        </div>
    </div>
{% endblock %}

django_engine/anatomy_main/atlases/templates/popular_atlases_component.html
{% load static %}
{% block popular_atlas %}
    <div class="mb-3">
        <h1 class="mb-2">Популярные атласы</h1>
        {% include "scrollable_atlases_cards_large.html" with atlases=popular_atlases %}
        <a href="{% url 'atlases:popular_atlases' %}"><button class="btn btn-primary btn-sm mt-2 rounded-4 shadow-lg"><span class='m-2' style="margin-right: 1px !important">Посмотреть все</span> <svg  xmlns="http://www.w3.org/2000/svg"  width="18"  height="18"  viewBox="0 0 24 24"  fill="currentColor"  class="icon icon-tabler icons-tabler-filled icon-tabler-circle-arrow-up-right"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-2 4.66h-6l-.117 .007a1 1 0 0 0 -.883 .993l.007 .117a1 1 0 0 0 .993 .883h3.584l-4.291 4.293l-.083 .094a1 1 0 0 0 1.497 1.32l4.293 -4.293v3.586l.007 .117a1 1 0 0 0 1.993 -.117v-6l-.007 -.117l-.029 -.149l-.035 -.105l-.054 -.113l-.071 -.111a1.01 1.01 0 0 0 -.097 -.112l-.09 -.08l-.096 -.067l-.098 -.052l-.11 -.044l-.112 -.03l-.126 -.017l-.075 -.003z" /></svg></button></a>
    </div>
{% endblock %}

django_engine/anatomy_main/atlases/templates/scrollable_atlases_cards.html
{% load static %}
{% block content %}
    <div class="scrollable-container" id="container">
            {% for atlas in atlases %}
                <a href="{{ atlas.get_absolute_url }}" style="text-decoration: none">
                    <div class="card little-card draggable border-0 rounded-4">
                        <img src="{% static atlas.atlas_file %}" class="card-img-top rounded-top-4" alt="...">
                        <div class="card-body p-0">
                            <div class="row d-flex justify-content-center text-center">
                                <div class="col-12 p-3">
                                    <span class="card-title">{{ atlas|truncatechars:20 }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
    </div>
{% endblock %}

django_engine/anatomy_main/atlases/templates/scrollable_atlases_cards_large.html
{% load static %}
{% block content %}
    <div class="scrollable-container" id="container">
            {% for atlas in atlases %}
                <div class="col-6 text-start d-flex justify-content-start text-center">
                    <a href="{{ atlas.get_absolute_url }}" style="text-decoration: none;">
                        <div class="card draggable-lg border-0 rounded-4">
                            <img src="{% static atlas.atlas_file %}" class="card-img-top rounded-top-4" alt="...">
                            <div class="card-body text-truncate">
                                <span>{{ atlas }}</span>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
    </div>
{% endblock %}