django_engine/anatomy_main/anatomy_main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import main, init_page, notes, delete_note, favorites

urlpatterns = [
    path('', init_page),
    path('home/', main, name='main'),
    path('admin/', admin.site.urls),
    path("tests/", include('tests.urls')),
    path("categories/", include('categories.urls')),
    path("articles/", include('articles.urls')),
    path('atlases/', include('atlases.urls'), name='atlases'),
    path("user/", include('users.urls')),
    path("notes/", notes, name='notes'),
    path('notes/delete_note/<str:object_id>', delete_note, name="delete_note"),
    path('favorites/', favorites, name='favorites')
]

django_engine/anatomy_main/articles/urls.py
from django.urls import path

from anatomy_main import view_builder
from . import views
from .models import Article

app_name = 'articles'

urlpatterns = [
    path('', views.main, name='main'),
    path('find/', view_builder.find(Article, "articles_main_page.html"), name='find'),
    path('find_preview/', view_builder.find(Article, "find_preview_articles_component.html", 5), name='find_preview'),
    path('open/<str:article_id>/', views.open_article, name='open_article'),
    path('popular_articles/', views.list_popular_articles, name='popular_articles'),
    path('favorite_articles/', views.list_favorite_articles, name='favorite_articles'),
    path('toggle_favorite_article/<str:article_id>/', views.toggle_favorite, name='add_to_favorite'),
    path('toggle_save_note/<str:article_id>/<str:note_text>/', views.toggle_save_note, name='toggle_save_note'),
    path('atlases/<str:article_id>', views.open_atlases_by_article, name='open_atlases_by_article'),
    path('articles/<str:article_id>', views.open_tests_by_article, name='open_tests_by_article')
]

django_engine/anatomy_main/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('list_user_completed_tests/', views.list_user_completed_tests, name='list_user_completed_tests'),
    # path('favorites/', views.favorites, name='favorites'),
    # path('notes/', views.notes, name='notes'),
]

django_engine/anatomy_main/articles/models.py
import uuid

from anatomy_main.models import BaseModel
from django.db import models
from django.urls import reverse
from users.models import ArticleUserRel


# Create your models here.


class Article(BaseModel):
    id = models.CharField(max_length=100, default=uuid.uuid4, primary_key=True)
    label = models.CharField(max_length=200, verbose_name='Название файла')
    article_file = models.FileField(verbose_name='Файл статьи',
                                    upload_to='articles_storage',
                                    null=True,
                                    blank=True)
    catalogs = models.ManyToManyField("categories.Catalog", verbose_name="Принадлежит каталогам",
                                      related_name='articles', blank=True)
    article_photo = models.ImageField(verbose_name='Фотография статьи',
                                      upload_to='articles_storage',
                                      blank=True)
    pdf_file = models.FileField(verbose_name='PDF-файл статьи',
                                upload_to='articles_storage',
                                null=True,
                                default=None,
                                blank=True)

    def catalog_ids(self):
        if self.catalogs.all():
            catalogs_array = [catalog for catalog in self.catalogs.all()]
            return catalogs_array
        return []

    def get_absolute_url(self):
        return reverse("articles:open_article",
                       kwargs={"article_id": self.id})

    @classmethod
    def get_popular(cls,
                    count: int, current_category=None):

        if current_category:
            exp = f"""WITH article_results AS (SELECT articles_article.* 
                                          FROM articles_article_catalogs 
                                          LEFT JOIN articles_article ON articles_article_catalogs.article_id = articles_article.id
                                          WHERE articles_article_catalogs.catalog_id = '{current_category.id}')
                                          SELECT article_results.*
                                          FROM article_results
                """
        else:
            exp = """SELECT article_results.*
                         FROM articles_article AS article_results"""
        
        res = cls.objects.raw(
            f"""
            {exp}
            left join (select articles_user.article_id,
                         count(articles_user.article_id) as fav_count
                  from articles_user
                  where articles_user.is_favorite
                  group by articles_user.article_id) as F on F.article_id = article_results.id
            order by F.fav_count DESC 
            """
        )
        return res[:count]

    @classmethod
    def get_favorite_articles(cls, user):
        return cls.objects.filter(
            id__in=ArticleUserRel
            .objects
            .filter(user=user, is_favorite=True)
            .values('article_id')
        ).annotate(
            is_favorite=models.Value(True, output_field=models.BooleanField())
        )

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.label

django_engine/anatomy_main/articles/views.py
import os

from anatomy_main import utils
from anatomy_main.settings import MEDIA_ROOT
from anatomy_main.utils import get_current_category
from articles.models import Article
from categories.models import Catalog
from django.db.models import Q
from django.http import HttpRequest
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from users.models import ArticleUserRel


# Create your views here.

def main(request: HttpRequest):
    current_category = get_current_category(request)

    popular_articles = Article.get_popular(10, current_category=current_category)
    favorite_articles = Article.get_favorite_articles(request.user)
    categories = Catalog.objects.all()
    return render(request, 'articles_main_page.html', {
        'popular_articles': popular_articles,
        'favorite_articles': favorite_articles,
        'categories': categories,
        'category': current_category
    })


def open_article(request: HttpRequest,
                 article_id: str):
    article = get_object_or_404(Article, id=article_id)
    file = article.article_file
    pdf_file = article.pdf_file

    article_user_rel: ArticleUserRel = ArticleUserRel.objects.get_or_create(user=request.user,
                                                                            article_id=article_id)[0]

    try:
        rel_field = ArticleUserRel.objects.get(article=article, user=request.user)
    except ArticleUserRel.DoesNotExist:
        note = ''
    else:
        note = rel_field.note

    article_content_path = os.path.join(MEDIA_ROOT, str(file)) if file else None
    return render(request,
                  'article.html',
                  {
                      "pdf": pdf_file.url if pdf_file else None,
                      "article": article,
                      "is_favorite": article_user_rel.is_favorite,
                      'tests': article.get_tests_by_categories(),
                      'articles': article.get_articles_by_categories(),
                      'article_content_path': (article_content_path
                                               if article_content_path and os.path.exists(article_content_path)
                                               else None),
                      "note": note
                  })


@require_POST
def toggle_favorite(request: HttpRequest,
                    article_id: str):
    return utils.toggle_favorite(request,
                                 article_id,
                                 ArticleUserRel,
                                 "article_id")


@require_POST
def toggle_save_note(request, article_id, note_text=''):
    return utils.toggle_save_note(request, article_id, ArticleUserRel, 'article_id', note_text)


def find(request: HttpRequest):
    queries = request.GET
    articles = Article.objects.filter(Q(label__icontains=queries.get('label', '')))
    return render(request, 'article_find.html', {'articles': articles})


def list_favorite_articles(request):
    return render(request, 'list_articles_page.html', context={"articles": Article.get_favorite_articles(request.user)})


def list_popular_articles(request):
    return render(request, 'list_articles_page.html', context={"articles": Article.get_popular(count=10)})


def open_atlases_by_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    return render(request, "list_atlases_page.html", context={"atlases": article.get_atlases_by_categories()})


def open_tests_by_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    return render(request, "list_tests_page.html", context={"tests": article.get_tests_by_categories()})

django_engine/anatomy_main/articles/templates/add_article_to_favorite.html
{% load static %}
<label>
    <button class="favorite-button btn-link p-0 m-0 w-100" style="border: 0; text-decoration: none; background: none" data-item-id="{{ article.id }}">
        {% if is_favorite %}<img id="test" src="{% static 'icons/star_black.svg' %}" class="star-icon">{% else %}<img id='test' src="{% static 'icons/star.svg' %}" class="star-icon">{% endif %}
    </button>
</label>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% csrf_token %}
<script>
const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
</script>
<script>
    $(document).ready(function() {
        $('.favorite-button ').click(function() {
            var button = $(this);
            var articleId = button.data('item-id');
            var oldIcon = document.getElementById('test')
            $.ajax({
                url: '/articles/toggle_favorite_article/' + articleId + '/',
                type: 'POST',
                headers: {
                    'X-CSRFToken': csrftoken
                },
                success: function(response) {
                    if (response.action === 'added') {
                        var newIcon = document.createElement('img')
                        newIcon.setAttribute('class', 'star-icon')
                        newIcon.setAttribute('id', 'test')
                        newIcon.setAttribute('src', "{% static 'icons/star_black.svg' %}")
                        oldIcon.parentNode.replaceChild(newIcon, oldIcon)
                        console.log(response.action)
                    } else {
                        var newIcon = document.createElement('img')
                        newIcon.setAttribute('class', 'star-icon')
                        newIcon.setAttribute('id', 'test')
                        newIcon.setAttribute('src', "{% static 'icons/star.svg' %}")
                        oldIcon.replaceWith(newIcon)
                        console.log(response.action)
                    }
                },
                error: function(xhr, status, error) {
                    console.error("Ошибка:", error);
                }
            });
        });
    });
</script>

django_engine/anatomy_main/articles/templates/add_note_to_article.html
<div class="input-group mb-3 mt-3 notes-component" style="border-radius: 20px;">
    <input type="text" name="note" class="form-control search-input rounded-start-pill border border-0 custom-focus" placeholder="Написать заметку по статье" style="border-right: none; border-color: rgb(0,0,0)" value="{{ note }}" id="textareaID">
    <button class="btn btn-outline-secondary rounded-end-circle save-button border border-0" style="border-left: none; border-color: rgb(0,0,0); background-color: white">
        <svg  xmlns="http://www.w3.org/2000/svg"  width="22"  height="22"  viewBox="0 0 24 24"  fill="none"  stroke="#113B3A"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-plus">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
            <path d="M12 5l0 14" /><path d="M5 12l14 0" />
        </svg>
    </button>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% csrf_token %}
<script>
    $(document).ready(function() {
        $('.save-button ').click(function() {
            var button = $(this);
            console.log(button)
            var note_text = document.getElementById('textareaID').value;
            $.ajax({
                url: '/articles/toggle_save_note/' + '{{ article.id }}' + "/" + note_text + (note_text ? '/' : ''),
                type: 'POST',
                headers: {
                    'X-CSRFToken': csrftoken
                },
                success: function(response) {
                    console.log(response)
                },
                error: function(xhr, status, error) {
                    console.error("Ошибка:", error);
                }
            });
        });
    });
</script>

django_engine/anatomy_main/articles/templates/article.html
{% include 'index.html' with active='articles' %}
{% load static %}
{% block content %}
    <div class="image-container p-0 m-0">
        <img class='p-0 m-0' src="{% static article.article_photo %}"
             style="width: 100%; height: 100%; max-height: 35vh; min-height: 35vh">
    </div>

    <div class="container p-4 content-box rounded-top-5 shadow-lg" style="padding-top: 0 !important;">

        <div class="container p-0 m-0">
            <div class="container p-3 text-center">
                <a class="icon-link" style="text-decoration: none; color: black">
                    {% include "add_article_to_favorite.html" %}
                    <h1 style="margin: 0; padding: 0" class="text-break"><b>{{ article.label }}</b></h1>
                </a>
                <!-- Кнопка поделиться с модальным окном -->
                <button class="btn btn-primary btn-sm mt-3 rounded-4 shadow-lg"
                        data-bs-toggle="modal"
                        data-bs-target="#shareModal">
                    <i class="bi bi-share"></i> Поделиться
                </button>
            </div>
        </div>

        <div class="container text-wrap text-break rounded"
             style="line-height: 20px; overflow: auto; margin-bottom: 15px">
            {% if article_content_path and not pdf %}
                {% include article_content_path %}
            {% elif pdf %}
                <pinch-zoom id="pdf-zoom" style="display:block; width: 100%; height: 400px;" class="rounded">
                    <canvas id="pdf-viewer" style="width: 100%; max-width: 100%;" class="rounded-4"></canvas>
                </pinch-zoom>
            {% else %}
                <span>Текст недоступен</span>
            {% endif %}
        </div>
        <hr class="hr-vet rounded" style="margin-bottom: 20px"/>
        <div class="container justify-content-center text-center p-2">
            {% include "add_note_to_article.html" with article=article %}
        </div>
        <h5 class="mt-2 mb-2">Тесты по теме</h5>
            <div class="mb-3">
                {% include 'scrollable_tests_cards.html' with tests=tests %}
                <a href="{% url 'articles:open_tests_by_article' article_id=article.id %}"><button class="btn btn-primary btn-sm mt-2 rounded-4 shadow-lg"><span class='m-2' style="margin-right: 1px !important">Посмотреть все</span> <svg  xmlns="http://www.w3.org/2000/svg"  width="18"  height="18"  viewBox="0 0 24 24"  fill="currentColor"  class="icon icon-tabler icons-tabler-filled icon-tabler-circle-arrow-up-right"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-2 4.66h-6l-.117 .007a1 1 0 0 0 -.883 .993l.007 .117a1 1 0 0 0 .993 .883h3.584l-4.291 4.293l-.083 .094a1 1 0 0 0 1.497 1.32l4.293 -4.293v3.586l.007 .117a1 1 0 0 0 1.993 -.117v-6l-.007 -.117l-.029 -.149l-.035 -.105l-.054 -.113l-.071 -.111a1.01 1.01 0 0 0 -.097 -.112l-.09 -.08l-.096 -.067l-.098 -.052l-.11 -.044l-.112 -.03l-.126 -.017l-.075 -.003z" /></svg></button></a>
            </div>
        <h5 class="mt-5 mb-2">Атласы по теме</h5>
            <div class="mb-3">
                {% include 'scrollable_atlases_cards.html' with articles=articles %}
                <a href="{% url 'articles:open_atlases_by_article' article_id=article.id %}"><button class="btn btn-primary btn-sm mt-2 rounded-4 shadow-lg"><span class='m-2' style="margin-right: 1px !important">Посмотреть все</span> <svg  xmlns="http://www.w3.org/2000/svg"  width="18"  height="18"  viewBox="0 0 24 24"  fill="currentColor"  class="icon icon-tabler icons-tabler-filled icon-tabler-circle-arrow-up-right"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-2 4.66h-6l-.117 .007a1 1 0 0 0 -.883 .993l.007 .117a1 1 0 0 0 .993 .883h3.584l-4.291 4.293l-.083 .094a1 1 0 0 0 1.497 1.32l4.293 -4.293v3.586l.007 .117a1 1 0 0 0 1.993 -.117v-6l-.007 -.117l-.029 -.149l-.035 -.105l-.054 -.113l-.071 -.111a1.01 1.01 0 0 0 -.097 -.112l-.09 -.08l-.096 -.067l-.098 -.052l-.11 -.044l-.112 -.03l-.126 -.017l-.075 -.003z" /></svg></button></a>
            </div>
    </div>

    <!-- Модальное окно для выбора способа шаринга -->
    <div class="modal fade" id="shareModal" tabindex="-1" aria-labelledby="shareModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="shareModalLabel">Поделиться статьей</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="d-grid gap-2">

                        <!-- Кнопка для системного шаринга -->
                        <button class="btn btn-primary shadow-lg" onclick="shareViaSystem()">
                            <i class="bi bi-share"></i> Через приложения
                        </button>

                        <!-- Кнопка для копирования ссылки -->
                        <button class="btn btn-primary shadow-lg"
                                onclick="copyLink(); $('#shareModal').modal('hide')">
                            <i class="bi bi-link-45deg"></i> Скопировать ссылку
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Генерация ссылки для шаринга
        function generateShareLink() {
            const articleId = "{{ article.id }}";
            return `https://t.me/vet_irit_bot?startapp=article_${articleId}`;
        }

        // Системный шаринг через Web Share API
        function shareViaSystem() {
            const shareData = {
                title: '{{ article.label }}',
                text: 'Посмотрите эту статью:',
                url: generateShareLink()
            };

            if (navigator.share) {
                navigator.share(shareData);
            } else {
                copyLink();
                alert('Ссылка скопирована в буфер обмена');
            }
        }

        // Копирование ссылки
        function copyLink() {
            const link = generateShareLink();
            navigator.clipboard.writeText(link).then(() => {
                if (window.Telegram && Telegram.WebApp) {
                    Telegram.WebApp.showAlert('Ссылка скопирована!');
                }
            });
        }

        // Инициализация
        document.addEventListener('DOMContentLoaded', function() {
            document.getElementById('share-link').value = generateShareLink();
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js"></script>
    <script>
        const url = '{% static pdf %}';

        const loadingTask = pdfjsLib.getDocument(url);
        loadingTask.promise.then(pdf => {
            pdf.getPage(1).then(page => {

                const viewport = page.getViewport({scale: 1});
                const canvas = document.getElementById('pdf-viewer');
                const context = canvas.getContext('2d');
                canvas.width = viewport.width;
                canvas.height = viewport.height;

                const renderContext = {
                    canvasContext: context,
                    viewport: viewport
                };

                page.render(renderContext);
                container.appendChild(canvas);
                const zoom_pdf = document.getElementById("pdf-zoom");
                zoom_pdf.addEventListener(
                    'pointerup', () => {
                        const containerWidth = container.clientWidth;

                        // Получаем оригинальные размеры страницы
                        const unscaledViewport = page.getViewport({scale: 1});

                        // Вычисляем нужный масштаб, чтобы влезло в контейнер
                        const scale = containerWidth / unscaledViewport.width;

                        const viewport = page.getViewport({scale: 1});

                        canvas.width = viewport.width;
                        canvas.height = viewport.height;
                        const renderContext = {
                            canvasContext: context,
                            viewport: viewport
                        };

                        page.render(renderContext);
                    }
                )
            });
        });
    </script>
    <script src="https://unpkg.com/@google/pinch-zoom"></script>
{% endblock %}

django_engine/anatomy_main/articles/templates/articles_main_page.html
{% include 'index.html' with active='articles' %}
{% load static %}
{% block content %}

    <div class="container p-4 pt-3">

        {% include 'current_category_label.html' with active='Категории' %}

        <form action="{% url 'articles:find' %}">
            <div class="input-group mb-3"
                 style="border-radius: 20px; position: relative;">
                <div class='input-group' style="position: relative; overflow: hidden; margin-bottom: -10px; !important">
                    <input name="label__icontains" type="text"
                           class="form-control search-input custom-focus rounded-start-pill notes-component"
                           placeholder="Найти статью"
                           style="border-right: none; background-color: white"
                           autocomplete="off">
                    <button class="btn btn-outline-secondary rounded-end-circle notes-component"
                            style="border-left: none; background-color: white">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none"
                             stroke="#113B3A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                             class="icon icon-tabler icons-tabler-outline icon-tabler-search">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M10 10m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"/>
                            <path d="M21 21l-6 -6"/>
                        </svg>
                    </button>
                </div>
                <!-- Выпадающее меню результатов -->
                <ul class="dropdown-menu w-100 shadow-lg" id="search-dropdown"
                    style="display: none; max-height: 200px; overflow-y: auto; margin-top: -10px; z-index: 1;">
                    <div id="search-results"></div>
                </ul>
            </div>
        </form>

        {% include "open_categories_button.html" %}

        {% if objects  is not None %}
            <div class="row text-center justify-content-between">
                {% if objects|length > 0 %}
                    <h1 class="p-1">Найденные статьи</h1>
                    {% include "grid_articles_cards.html" with articles=objects %}
                {% else %}
                    <h1 class="p-1">Ничего не найдено</h1>
                {% endif %}
            </div>
        {% else %}
            <div class="pb-3 pt-3">
                {% include 'popular_articles_component.html' with popular_articles=popular_articles %}
            </div>
            <div class="pb-3">
                {% include 'favorite_articles_component.html' with favorite_articles=favorite_articles %}
            </div>
        {% endif %}
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const searchInput = document.querySelector(".search-input");
            const resultsContainer = document.querySelector("#search-results");
            const searchDropdown = document.querySelector("#search-dropdown");

            // Функция для показа/скрытия выпадающего меню
            function toggleDropdown(show) {
                searchDropdown.style.display = show ? "block" : "none";
            }

            // Закрытие меню при клике вне области
            document.addEventListener("click", function (e) {
                if (!e.target.closest(".input-group")) {
                    toggleDropdown(false);
                }
            });

            function debounce(func, delay) {
                let timeout;
                return function (...args) {
                    clearTimeout(timeout);
                    timeout = setTimeout(() => func.apply(this, args), delay);
                };
            }

            function performSearch() {
                const query = searchInput.value.trim();

                if (!query) {
                    resultsContainer.innerHTML = "";
                    toggleDropdown(false);
                    return;
                }

                toggleDropdown(true);

                fetch(`find_preview/?label__icontains=${encodeURIComponent(query)}`)
                    .then(response => {
                        if (!response.ok) throw new Error("Network response was not ok");
                        return response.text();
                    })
                    .then(html => {
                        resultsContainer.innerHTML = html;

                        // Добавляем обработчики для элементов меню
                        document.querySelectorAll("#search-dropdown .dropdown-item").forEach(item => {
                            item.addEventListener("click", function () {
                                toggleDropdown(false);
                            });
                        });
                    })
                    .catch(() => {
                        resultsContainer.innerHTML = `
                    <div class="dropdown-item text-danger">
                        Произошла ошибка. Попробуйте снова.
                    </div>`;
                    });
            }

            const debouncedSearch = debounce(performSearch, 300);

            searchInput.addEventListener("input", debouncedSearch);
            searchInput.addEventListener("focus", function () {
                if (searchInput.value.trim() && resultsContainer.innerHTML) {
                    toggleDropdown(true);
                }
            });
        });
    </script>
{% endblock %}

django_engine/anatomy_main/articles/templates/favorite_articles_component.html
{% load static %}
{% block popular_article %}
    <div class="mb-3">
        <h1 class="mb-2">Избранные статьи</h1>
        {% include "scrollable_articles_cards_large.html" with articles=favorite_articles %}
        <a href="{% url 'articles:favorite_articles' %}"><button class="btn btn-primary btn-sm mt-2 rounded-4 shadow-lg"><span class='m-2' style="margin-right: 1px !important">Посмотреть все</span> <svg  xmlns="http://www.w3.org/2000/svg"  width="18"  height="18"  viewBox="0 0 24 24"  fill="currentColor"  class="icon icon-tabler icons-tabler-filled icon-tabler-circle-arrow-up-right"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-2 4.66h-6l-.117 .007a1 1 0 0 0 -.883 .993l.007 .117a1 1 0 0 0 .993 .883h3.584l-4.291 4.293l-.083 .094a1 1 0 0 0 1.497 1.32l4.293 -4.293v3.586l.007 .117a1 1 0 0 0 1.993 -.117v-6l-.007 -.117l-.029 -.149l-.035 -.105l-.054 -.113l-.071 -.111a1.01 1.01 0 0 0 -.097 -.112l-.09 -.08l-.096 -.067l-.098 -.052l-.11 -.044l-.112 -.03l-.126 -.017l-.075 -.003z" /></svg></button></a>
    </div>
{% endblock %}

django_engine/anatomy_main/articles/templates/find_preview_articles_component.html
{% load static %}
{% block find_preview_article %}
    <div class="mt-3 text-start">
        {% if objects|length > 0 %}
            {% for article in objects %}
            <li>
                <a class='dropdown-item' href="{{ article.get_absolute_url }}" style="text-decoration: none;">
                    <h4>{{ article }}</h4>
                    {% if article.description %}
                        {{ article.description }}
                    {% else %}
                        <span>Описание отсутствует</span>
                    {% endif %}
                </a>
            </li>
            {% endfor %}
        {% else %}
            <div class="text-center mt-4">
                <p>Ничего не найдено</p>
            </div>
        {% endif %}
    </div>
{% endblock %}

django_engine/anatomy_main/articles/templates/grid_articles_cards.html
{% load static %}
{% block content %}
    {% for article in articles %}
        <div class="col-6 p-1 text-start d-flex justify-content-center text-center">
            <a href="{{ article.get_absolute_url }}" style="text-decoration: none;">
                <div class="card draggable-lg border-0 shadow rounded-4">
                    <img src="{% static article.article_photo %}" class="card-img-top rounded-top-4" alt="..." onerror="this.src='{% static "alternate_imgs/kotek.png" %}'; this.onerror=null;">
                    <div class="card-body text-truncate">
                        <span>{{ article }}</span>
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
{% endblock %}

django_engine/anatomy_main/articles/templates/popular_articles_component.html
{% load static %}
{% block popular_article %}
    <div class="mb-3">
        <h1 class="mb-2">Популярные статьи</h1>
        {% include "scrollable_articles_cards_large.html" with articles=popular_articles %}
        <a href="{% url 'articles:popular_articles' %}"><button class="btn btn-primary btn-sm mt-2 rounded-4 shadow-lg"><span class='m-2' style="margin-right: 1px !important">Посмотреть все</span> <svg  xmlns="http://www.w3.org/2000/svg"  width="18"  height="18"  viewBox="0 0 24 24"  fill="currentColor"  class="icon icon-tabler icons-tabler-filled icon-tabler-circle-arrow-up-right"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-2 4.66h-6l-.117 .007a1 1 0 0 0 -.883 .993l.007 .117a1 1 0 0 0 .993 .883h3.584l-4.291 4.293l-.083 .094a1 1 0 0 0 1.497 1.32l4.293 -4.293v3.586l.007 .117a1 1 0 0 0 1.993 -.117v-6l-.007 -.117l-.029 -.149l-.035 -.105l-.054 -.113l-.071 -.111a1.01 1.01 0 0 0 -.097 -.112l-.09 -.08l-.096 -.067l-.098 -.052l-.11 -.044l-.112 -.03l-.126 -.017l-.075 -.003z" /></svg></button></a>
    </div>
{% endblock %}